import os
import json
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ── Rate Limiter (limits applied in M5; configured here so the decorator is ready) ──
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Groq client ──────────────────────────────────────────────────────────────
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ── Audit Log ─────────────────────────────────────────────────────────────────
LOG_FILE = "audit_log.json"


def load_log() -> list:
    """Return all existing audit-log entries (empty list if file doesn't exist yet)."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def append_log(entry: dict) -> None:
    """Append a single structured entry to the audit log."""
    entries = load_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def update_log_entry(content_id: str, updates: dict) -> bool:
    """
    Find the log entry for content_id and apply updates in-place.
    Returns True if found, False otherwise.
    """
    entries = load_log()
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            with open(LOG_FILE, "w") as f:
                json.dump(entries, f, indent=2)
            return True
    return False


# ── Signal 1: LLM Holistic Check (Groq) ──────────────────────────────────────

def signal_llm(text: str) -> tuple[float, str]:
    """
    Ask the LLM to holistically assess whether the text is AI- or human-written.

    Captures: semantic coherence, tone uniformity, vagueness, and stylistic feel —
    properties that are hard to measure statistically but that a language model can
    pick up on because it has seen vast amounts of both kinds of writing.

    Blind spots: (1) confident writers who happen to write cleanly may score high;
    (2) the verdict is not reproducible — small prompt changes shift scores.

    Returns:
        score     float in [0.0, 1.0]  — 0 = likely human, 1 = likely AI
        reasoning str                  — one-sentence explanation from the model
    """
    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and estimate the probability that it was generated by an AI.

Key indicators of AI text:
- Uniform sentence rhythm and length
- Generic, hedged, or vague phrasing ("it is important to note", "various", "moreover")
- Polished but impersonal tone
- Lack of personal voice, typos, or idiosyncratic word choices

Key indicators of human text:
- Irregular sentence length and punctuation
- Personal anecdotes, colloquial language, or raw emotion
- Minor inconsistencies or informal construction
- Distinctive vocabulary or unusual phrasing

Respond ONLY with a JSON object in this exact format (no markdown, no extra keys):
{{"score": <float 0.0–1.0>, "reasoning": "<one sentence>"}}

score = 0.0 means definitely human-written.
score = 1.0 means definitely AI-generated.

Text to analyze:
\"\"\"
{text}
\"\"\"
"""

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=200,
        temperature=0.1,  # Low temperature for consistent scoring
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences if the model wraps its output anyway
    if raw.startswith("```"):
        parts = raw.split("```")
        raw = parts[1] if len(parts) > 1 else parts[0]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    parsed = json.loads(raw)
    score = max(0.0, min(1.0, float(parsed["score"])))   # clamp to [0, 1]
    reasoning = parsed.get("reasoning", "")
    return score, reasoning


# ── Confidence Scoring ────────────────────────────────────────────────────────
# M3 placeholder: only Signal 1 is wired in.
# M4 will replace this with a weighted average of both signals.

def compute_confidence(llm_score: float, stylometric_score: float | None = None) -> float:
    """
    Combine signal scores into a single calibrated confidence score (0–1).

    M3: returns LLM score directly (Signal 2 not yet implemented).
    M4: will apply weighted average → 0.6 * llm + 0.4 * stylometric.
    """
    if stylometric_score is None:
        return llm_score  # Temporary until M4
    # M4 will replace the line above with something like:
    # return round(0.6 * llm_score + 0.4 * stylometric_score, 4)
    return llm_score


# ── Label Generator ───────────────────────────────────────────────────────────
# Thresholds from planning.md:
#   likely_human  : confidence <= 0.40
#   uncertain     : 0.40 < confidence < 0.70
#   likely_ai     : confidence >= 0.70

def generate_label(confidence: float) -> dict:
    """
    Map a confidence score to one of three transparency labels.
    Returns a dict with keys: verdict (str), label (str).
    """
    if confidence >= 0.70:
        return {
            "verdict": "likely_ai",
            "label": (
                "⚠️ Likely AI-generated. Our analysis suggests this content was probably "
                "created with AI assistance (confidence: high). This is an automated estimate, "
                "not a certainty. If you're the creator and disagree, you can appeal this label."
            ),
        }
    elif confidence <= 0.40:
        return {
            "verdict": "likely_human",
            "label": (
                "✓ Likely human-written. Our analysis found no strong signs of AI generation "
                "(confidence: high). This is an automated estimate and not a guarantee of authorship."
            ),
        }
    else:
        return {
            "verdict": "uncertain",
            "label": (
                "❓ Inconclusive. Our analysis couldn't confidently determine whether this content "
                "was human- or AI-written. We're showing this honestly rather than guessing. "
                "No attribution claim is being made."
            ),
        }


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
# M5 will add: @limiter.limit("10 per minute;100 per day")
def submit():
    """
    Accept a piece of text for attribution analysis.

    Request body (JSON):
        text        str  — the content to classify
        creator_id  str  — identifier for the submitting creator

    Response (JSON):
        content_id    str   — unique ID for this submission (save for /appeal)
        attribution   str   — verdict: "likely_ai" | "uncertain" | "likely_human"
        confidence    float — combined score in [0, 1]
        label         str   — plain-language transparency label
        signals       dict  — individual signal scores
    """
    data = request.get_json(force=True, silent=True)
    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    text = (data.get("text") or "").strip()
    creator_id = (data.get("creator_id") or "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # ── Signal 1 ──
    llm_score, llm_reasoning = signal_llm(text)

    # ── Signal 2 placeholder (M4) ──
    stylometric_score = None

    # ── Combine into confidence ──
    confidence = compute_confidence(llm_score, stylometric_score)

    # ── Generate transparency label ──
    label_data = generate_label(confidence)

    # ── Write structured audit-log entry ──
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": label_data["verdict"],
        "confidence": round(confidence, 4),
        "llm_score": round(llm_score, 4),
        "llm_reasoning": llm_reasoning,
        "stylometric_score": stylometric_score,  # None until M4
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": label_data["verdict"],
        "confidence": round(confidence, 4),
        "label": label_data["label"],
        "signals": {
            "llm_score": round(llm_score, 4),
            "stylometric_score": stylometric_score,  # None until M4
        },
    })


@app.route("/log", methods=["GET"])
def get_log():
    """
    Return the most recent audit-log entries for inspection and grading.
    In a real system this would require authentication.
    """
    entries = load_log()
    return jsonify({
        "total": len(entries),
        "entries": entries[-20:],  # Most recent 20
    })


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True)