import os
import json
import uuid
from datetime import datetime, timezone

from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ── Rate Limiter (limits applied in M5; configured here so the decorator is ready) ──
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Groq client ──────────────────────────────────────────────────────────────
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ── Audit Log ─────────────────────────────────────────────────────────────────
LOG_FILE = "audit_log.json"


def load_log() -> list:
    """Return all existing audit-log entries (empty list if file doesn't exist yet)."""
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def append_log(entry: dict) -> None:
    """Append a single structured entry to the audit log."""
    entries = load_log()
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def update_log_entry(content_id: str, updates: dict) -> bool:
    """
    Find the log entry for content_id and apply updates in-place.
    Returns True if found, False otherwise.
    """
    entries = load_log()
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            with open(LOG_FILE, "w") as f:
                json.dump(entries, f, indent=2)
            return True
    return False


# ── Signal 1: LLM Holistic Check (Groq) ──────────────────────────────────────

def signal_llm(text: str) -> tuple[float, str]:
    """
    Ask the LLM to holistically assess whether the text is AI- or human-written.

    Captures: semantic coherence, tone uniformity, vagueness, and stylistic feel —
    properties that are hard to measure statistically but that a language model can
    pick up on because it has seen vast amounts of both kinds of writing.

    Blind spots: (1) confident writers who happen to write cleanly may score high;
    (2) the verdict is not reproducible — small prompt changes shift scores.

    Returns:
        score     float in [0.0, 1.0]  — 0 = likely human, 1 = likely AI
        reasoning str                  — one-sentence explanation from the model
    """
    prompt = f"""You are an expert at distinguishing AI-generated text from human-written text.

Analyze the following text and estimate the probability that it was generated by an AI.

Key indicators of AI text:
- Uniform sentence rhythm and length
- Generic, hedged, or vague phrasing ("it is important to note", "various", "moreover")
- Polished but impersonal tone
- Lack of personal voice, typos, or idiosyncratic word choices

Key indicators of human text:
- Irregular sentence length and punctuation
- Personal anecdotes, colloquial language, or raw emotion
- Minor inconsistencies or informal construction
- Distinctive vocabulary or unusual phrasing

Respond ONLY with a JSON object in this exact format (no markdown, no extra keys):
{{"score": <float 0.0–1.0>, "reasoning": "<one sentence>"}}

score = 0.0 means definitely human-written.
score = 1.0 means definitely AI-generated.

Text to analyze:
\"\"\"
{text}
\"\"\"
"""

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=200,
        temperature=0.1,  # Low temperature for consistent scoring
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences if the model wraps its output anyway
    if raw.startswith("```"):
        parts = raw.split("```")
        raw = parts[1] if len(parts) > 1 else parts[0]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    parsed = json.loads(raw)
    score = max(0.0, min(1.0, float(parsed["score"])))   # clamp to [0, 1]
    reasoning = parsed.get("reasoning", "")
    return score, reasoning


# ── Signal 2: Stylometric Heuristics ─────────────────────────────────────────

def signal_stylometric(text: str) -> tuple[float, dict]:
    """
    Measure statistical properties of text that differ between AI and human writing.

    Captures: structural uniformity — things the LLM signal misses because it reasons
    about meaning rather than raw form. AI tends to produce sentences of similar length
    with consistent rhythm; human writing is messier and more varied.

    Three metrics:
      1. Sentence-length variance   — low std dev → uniform → AI
      2. Type-token ratio (TTR)     — unique_words / total_words; lower → more repetitive → AI
      3. Expressive punctuation     — !, ?, —, … etc.; lower density → AI

    Blind spots: (1) short texts (< ~30 words) give unreliable statistics — the function
    returns a neutral 0.5 in that case; (2) writers who naturally produce clean, uniform
    prose (e.g. academic authors) may score higher than expected.

    Returns:
        score     float in [0.0, 1.0]  — 0 = structurally human-like, 1 = structurally AI-like
        breakdown dict                 — individual metric values for audit log / debugging
    """
    import re
    import math

    # ── Tokenise ──
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r"\b[a-zA-Z']+\b", text.lower())

    # Guard: too short to measure reliably
    if len(sentences) < 2 or len(words) < 20:
        return 0.5, {"note": "text too short for reliable stylometric analysis",
                     "sentence_count": len(sentences), "word_count": len(words)}

    # ── Metric 1: Sentence-length variance ──
    # AI text → sentences cluster tightly around a mean → low std dev → high AI score
    sent_lengths = [len(re.findall(r"\b[a-zA-Z']+\b", s)) for s in sentences]
    mean_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - mean_len) ** 2 for l in sent_lengths) / len(sent_lengths)
    std_dev = math.sqrt(variance)

    # Normalise: std_dev 0 → score 1.0 (very AI); std_dev ≥ 12 → score 0.0 (very human)
    len_var_score = max(0.0, min(1.0, 1.0 - (std_dev / 12.0)))

    # ── Metric 2: Type-token ratio (vocabulary diversity) ──
    # Lower TTR → more word repetition → more AI-like
    ttr = len(set(words)) / len(words)

    # Normalise: TTR 1.0 → score 0.0 (diverse = human); TTR 0.3 → score 1.0 (repetitive = AI)
    # Clamp so short-text TTR inflation doesn't break the range
    ttr_score = max(0.0, min(1.0, 1.0 - ttr))

    # ── Metric 3: Expressive punctuation density ──
    # Humans use !, ?, —, –, …, ; more freely; AI sticks to . and ,
    expressive = len(re.findall(r'[!?;:\-–—…]', text))
    punct_density = expressive / len(words)

    # Normalise: density 0 → score 1.0 (no expressiveness = AI); density ≥ 0.15 → score 0.0
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.15)))

    # ── Combine three sub-scores with equal weight ──
    combined = (len_var_score + ttr_score + punct_score) / 3.0

    breakdown = {
        "sentence_count": len(sentences),
        "word_count": len(words),
        "sentence_length_std_dev": round(std_dev, 2),
        "len_variance_ai_score": round(len_var_score, 4),
        "type_token_ratio": round(ttr, 4),
        "ttr_ai_score": round(ttr_score, 4),
        "expressive_punct_density": round(punct_density, 4),
        "punct_ai_score": round(punct_score, 4),
    }

    return round(combined, 4), breakdown


# ── Confidence Scoring ────────────────────────────────────────────────────────

def compute_confidence(llm_score: float, stylometric_score: float) -> float:
    """
    Combine both signal scores into a single calibrated confidence score (0–1).

    Weights (from planning.md):
        LLM signal         60% — holistic semantic judgement; stronger signal overall
        Stylometric signal 40% — structural statistics; independent cross-check

    The LLM is weighted higher because it captures meaning and tone, not just form.
    A good writer with unusual structure shouldn't be over-penalised by stylometrics alone.
    """
    return round(0.6 * llm_score + 0.4 * stylometric_score, 4)


# ── Label Generator ───────────────────────────────────────────────────────────
# Thresholds from planning.md:
#   likely_human  : confidence <= 0.40
#   uncertain     : 0.40 < confidence < 0.70
#   likely_ai     : confidence >= 0.70

def generate_label(confidence: float) -> dict:
    """
    Map a confidence score to one of three transparency labels.
    Returns a dict with keys: verdict (str), label (str).
    """
    if confidence >= 0.70:
        return {
            "verdict": "likely_ai",
            "label": (
                "⚠️ Likely AI-generated. Our analysis suggests this content was probably "
                "created with AI assistance (confidence: high). This is an automated estimate, "
                "not a certainty. If you're the creator and disagree, you can appeal this label."
            ),
        }
    elif confidence <= 0.40:
        return {
            "verdict": "likely_human",
            "label": (
                "✓ Likely human-written. Our analysis found no strong signs of AI generation "
                "(confidence: high). This is an automated estimate and not a guarantee of authorship."
            ),
        }
    else:
        return {
            "verdict": "uncertain",
            "label": (
                "❓ Inconclusive. Our analysis couldn't confidently determine whether this content "
                "was human- or AI-written. We're showing this honestly rather than guessing. "
                "No attribution claim is being made."
            ),
        }


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
# M5 will add: @limiter.limit("10 per minute;100 per day")
def submit():
    """
    Accept a piece of text for attribution analysis.

    Request body (JSON):
        text        str  — the content to classify
        creator_id  str  — identifier for the submitting creator

    Response (JSON):
        content_id    str   — unique ID for this submission (save for /appeal)
        attribution   str   — verdict: "likely_ai" | "uncertain" | "likely_human"
        confidence    float — combined score in [0, 1]
        label         str   — plain-language transparency label
        signals       dict  — individual signal scores
    """
    data = request.get_json(force=True, silent=True)
    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    text = (data.get("text") or "").strip()
    creator_id = (data.get("creator_id") or "").strip()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # ── Signal 1: LLM holistic check ──
    llm_score, llm_reasoning = signal_llm(text)

    # ── Signal 2: Stylometric heuristics ──
    stylometric_score, stylo_breakdown = signal_stylometric(text)

    # ── Combine into confidence (60% LLM, 40% stylometric) ──
    confidence = compute_confidence(llm_score, stylometric_score)

    # ── Generate transparency label ──
    label_data = generate_label(confidence)

    # ── Write structured audit-log entry ──
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": label_data["verdict"],
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "llm_reasoning": llm_reasoning,
        "stylometric_score": stylometric_score,
        "stylometric_breakdown": stylo_breakdown,
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": label_data["verdict"],
        "confidence": confidence,
        "label": label_data["label"],
        "signals": {
            "llm_score": round(llm_score, 4),
            "stylometric_score": stylometric_score,
            "stylometric_breakdown": stylo_breakdown,
        },
    })


@app.route("/log", methods=["GET"])
def get_log():
    """
    Return the most recent audit-log entries for inspection and grading.
    In a real system this would require authentication.
    """
    entries = load_log()
    return jsonify({
        "total": len(entries),
        "entries": entries[-20:],  # Most recent 20
    })


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True)